# remote_theme: benbalter/retlab
# remote_theme: oinam/oinam-jekyll
# remote_theme: daattali/beautiful-jekyll@6.0.1
remote_theme: mmistakes/so-simple-theme@3.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-scholar

repository: msdbok/sqrbok
title: Software Quality and Reliability Body of Knowledge
description: Course notes on software quality assurance and management


collections:
  definition:
    output: true
  oranization:
    output: true
  verification:
    output: true
  properties:
    output: true
  material:
    output: true


scholar:
  style: ieee